name: Databricks CI/CD

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------- CHECKOUT ----------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------------- INSTALL DATABRICKS CLI ----------------
      - name: Install Databricks CLI (New)
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks version

      # ---------------- SET ENV VARIABLES ----------------
      - name: Set Databricks Environment
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      # ---------------- DEV DEPLOYMENT ----------------
      - name: Deploy to DEV Workspace
        if: github.event_name == 'push'
        run: |
          databricks workspace import-dir . /Users/${{ github.actor }}/dev --overwrite

      # ---------------- PROD DEPLOYMENT ----------------
      - name: Deploy to PROD Workspace
        if: github.event.pull_request.merged == true && github.base_ref == 'main'
        run: |
          databricks workspace import-dir . /Users/${{ github.actor }}/prod --overwrite
