name: Databricks CI/CD

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      # ---------------- DEV DEPLOYMENT ----------------
      - name: Deploy to DEV
        if: github.event_name == 'push'
        run: |
          databricks workspace import demo.py /Users/${{ github.actor }}/dev/demo --overwrite

      # ---------------- PROD DEPLOYMENT ----------------
      - name: Deploy to PROD
        if: github.event_name == 'pull_request' && github.base_ref == 'main' && github.event.pull_request.merged == true
        run: |
          databricks workspace import demo.py /Users/${{ github.actor }}/prod/demo --overwrite
